version: '3.8'
services:
  nginx:
    image:
      leebolim0701471/frontend-lb:1.0
    ports:
      - "88:80"
    depends_on:
      - frontend
    networks:
      - frontend-network
  frontend:
    image:
      dbgurum/guestbook:frontend_1.0
    ports:
      - "10001-10003:8000"
    networks:
      - frontend-network
    environment:
      PORT: 8000
      GUESTBOOK_API_ADDR: haproxy:8000
    deploy:
      replicas: 3
      mode: replicated
  haproxy:
    image:
      leebolim0701471/haproxy:6.0
    ports:
      - "7999-8000:80"
      - "9000-9001:9000"
    deploy:
      replicas: 2
      mode: replicated
    depends_on:
      - backend
    networks:
      - frontend-network
      - backend-network
  backend:
    ports:
      - "8001-8003:8000"
    environment:
      PORT: 8000
      GUESTBOOK_DB_ADDR: mongo:27017
    networks:
      - backend-network
    image:
      leebolim0701471/agora-backend:2.0
    deploy:
      replicas: 3
      mode: replicated
    depends_on:
      - mongo
  mongo:
    ports:
      - "17017:27017"
    image:
      mongo:4
    networks:
      - backend-network

networks:
  frontend-network: 
    ipam:
        driver: default
        config:
          - subnet: 172.28.0.0/16
  backend-network:
    ipam:
        driver: default
        config:
          - subnet: 172.29.0.0/16